/* ORGANIZAÇÃO DAS CHAVES - CONSTRAINT */

CREATE TABLE JOGADOR (

    IDJOGADOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (30)

);


CREATE TABLE TIMES (

    IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	NOMETIME VARCHAR (30),
	ID_JOGADOR INT,
	FOREIGN KEY (ID_JOGADOR)
	REFERENCES JOGADOR (IDJOGADOR)

);


INSERT INTO JOGADOR VALUES(NULL,'GUERREIRO');
INSERT INTO TIMES VALUES(NULL,'FLAMENGO',1);

SELECT * FROM JOGADOR;

+-----------+-----------+
| IDJOGADOR | NOME      |
+-----------+-----------+
|         1 | GUERREIRO |
+-----------+-----------+

/* ----------------------------------------------------------------------------- */

SHOW CREATE TABLE JOGADOR;
SHOW CREATE TABLE TIMES;