/* Delimitador */

SELECT  C.NOME, 
		C.SEXO, 
		IFNULL(C.EMAIL,'CLIENTE SEM EMAIL') AS "E-MAIL", 
		T.TIPO, 
		T.NUMERO, 
		E.BAIRRO, 
		E.CIDADE, 
		E.ESTADO
FROM CLIENTE C 
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE 
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
ORDER BY 1; -- O BANCO ESPERA VOCÊ DELIMITAR O SCRIPT

STATUS -- COMANDO DE INFRAESTRUTURA (NÃO PRECISA DE DELIMITADOR)

DELIMITER $ -- MUDANDO O DELIMITADORC

SELECT * FROM V_RELATORIO; -- ELE VAI IGNORAR O ;, POIS O DELIMITADOR FOI ALTERADO

DELIMITER ;