/* MODELAGEM BÁSICA */

CLIENTE

NOME - CARACTER (30)
CPF - NUMÉRICO (11)
EMAIL - CARACTER (30)
TELEFONE - CARACTER (30)
ENDEREÇO - CARACTER (100)
SEXO - CARACTER (1)

/* PROCESSOS DE MODELAGEM*/

/* FASE 01 E 02 - AD ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE EXEMPLO;

CREATE DATABASE PROJECT;

/* CONECTAND-SE AO BANCO */

USE PROJECT;

/* CRIANDO A TABELA DE CLIENTES */

CREATE TABLE CLIENTE (
    NOME VARCHAR (30),
	SEXO CHAR (1),
	EMAIL VARCHAR (30),
	CPF INT (11),
	TELEFONE VARCHAR (30),
	ENDEREÇO VARCHAR (100)
	/* COPIAR E COLAR NO PROMPT DE COMANDO*/
);

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;  /* SÓ EXISTE NO MYSQL */

/* DESCOBRINDO A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;

/* SINTAXE BASICA DE INSERÇÃO - INSERT INTO TABELA... */

/* FORMA 01 - OMITINDO AS COLUNAS (FORMA MENOS SEGURA) */

INSERT INTO CLIENTE VALUES ('JOÃO','M','JOÃO@GMAIL.COM',988638273,'229231110','MAIA LACERDA-ESTACIO,RJ');

INSERT INTO CLIENTE VALUES ('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO-CENTRO,RJ');

INSERT INTO CLIENTE VALUES ('JORGE','M',NULL,885755896,'58748895','BOM RETIRO-PATO DE MINAS,MG');


/* FORMA 02 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE (NOME, SEXO, ENDEREÇO, TELEFONE, CPF) VALUES ('LILIAN','F','SENADOR SOARES-TIJUCA,RJ','947785696',887774856);
				
				
/* FORMA 03 - INSERT COMPACTO (SOMENTE MYSQL) */

INSERT INTO CLIENTE VALUES ('ANA','F','ANA@GLABO.COM', 85548962,'548553685','PRES. ANTÔNIO CARLOS-CENTRO,SP'),
                  ('CARLA','F','CARLA@GLABO.COM',7745828,'66587458','SAMUEL SILVA-CENTRO,MG');
				
/* COMANDO SELECT 

SELEÇÃO, PROJEÇÃO (SELECT) E JUNÇÃO 
*/

SELECT NOW() AS DATA_HORA, 'JULIA BARROS' AS EU;

SELECT 'JULIA BARROS';
SELECT 'BANCO DE DADOS';


/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDEREÇO FROM CLIENTE;


/* APENAS PARA FINS ACADÊMICOS */

SELECT * FROM CLIENTE;

CREATE TABLE CLIENTE (
    NOME VARCHAR (30),
	SEXO CHAR (1),
	EMAIL VARCHAR (30),
	CPF INT (11),
	TELEFONE VARCHAR (30),
	ENDEREÇO VARCHAR (100)
	/* COPIAR E COLAR NO PROMPT DE COMANDO*/
);


/* FILTRANDO DADOS COM WHERE E LIKE */

SELECT NOME, TELEFONE FROM CLIENTE;


/* FILTRANDO */

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDEREÇO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDEREÇO = 'RJ';


/* UTILIZANDO LIKE */

SELECT NOME, SEXO, ENDEREÇO FROM CLIENTE
WHERE ENDEREÇO LIKE '%RJ';
/* % : ELEMENTO CORINGA - QUALQUER COISA*/

SELECT NOME, SEXO, ENDEREÇO FROM CLIENTE
WHERE ENDEREÇO LIKE '%CENTRO%';