/* MODELAGEM BÁSICA */

CLIENTE

NOME - CARACTER (30)
CPF - NUMÉRICO (11)
EMAIL - CARACTER (30)
TELEFONE - CARACTER (30)
ENDEREÇO - CARACTER (100)
SEXO - CARACTER (1)

/* PROCESSOS DE MODELAGEM*/

/* FASE 01 E 02 - AD ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE EXEMPLO;

CREATE DATABASE PROJECT;

/* CONECTAND-SE AO BANCO */

USE PROJECT;

/* CRIANDO A TABELA DE CLIENTES */

CREATE TABLE CLIENTE (
    NOME VARCHAR (30),
	SEXO CHAR (1),
	EMAIL VARCHAR (30),
	CPF INT (11),
	TELEFONE VARCHAR (30),
	ENDEREÇO VARCHAR (100)
	/* COPIAR E COLAR NO PROMPT DE COMANDO*/
);

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;  /* SÓ EXISTE NO MYSQL */

/* DESCOBRINDO A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;

/* SINTAXE BASICA DE INSERÇÃO - INSERT INTO TABELA... */

/* FORMA 01 - OMITINDO AS COLUNAS (FORMA MENOS SEGURA) */

INSERT INTO CLIENTE VALUES ('JOÃO','M','JOÃO@GMAIL.COM',988638273,'229231110','MAIA LACERDA-ESTACIO,RJ');

INSERT INTO CLIENTE VALUES ('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO-CENTRO,RJ');

INSERT INTO CLIENTE VALUES ('JORGE','M',NULL,885755896,'58748895','BOM RETIRO-PATO DE MINAS,MG');


/* FORMA 02 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE (NOME, SEXO, ENDEREÇO, TELEFONE, CPF) VALUES ('LILIAN','F','SENADOR SOARES-TIJUCA,RJ','947785696',887774856);
				
				
/* FORMA 03 - INSERT COMPACTO (SOMENTE MYSQL) */

INSERT INTO CLIENTE VALUES ('ANA','F','ANA@GLABO.COM', 85548962,'548553685','PRES. ANTÔNIO CARLOS-CENTRO,SP'),
                  ('CARLA','F','CARLA@GLABO.COM',7745828,'66587458','SAMUEL SILVA-CENTRO,MG');
				
/* COMANDO SELECT 

SELEÇÃO, PROJEÇÃO (SELECT) E JUNÇÃO 
*/

SELECT NOW() AS DATA_HORA, 'JULIA BARROS' AS EU;

SELECT 'JULIA BARROS';
SELECT 'BANCO DE DADOS';


/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDEREÇO FROM CLIENTE;


/* APENAS PARA FINS ACADÊMICOS */

SELECT * FROM CLIENTE;

CREATE TABLE CLIENTE (
    NOME VARCHAR (30),
	SEXO CHAR (1),
	EMAIL VARCHAR (30),
	CPF INT (11),
	TELEFONE VARCHAR (30),
	ENDEREÇO VARCHAR (100)
	/* COPIAR E COLAR NO PROMPT DE COMANDO*/
);


/* FILTRANDO DADOS COM WHERE E LIKE */

SELECT NOME, TELEFONE FROM CLIENTE;


/* FILTRANDO */

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDEREÇO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDEREÇO = 'RJ';


/* UTILIZANDO LIKE */

SELECT NOME, SEXO, ENDEREÇO FROM CLIENTE
WHERE ENDEREÇO LIKE '%RJ';
/* % : ELEMENTO CORINGA - QUALQUER COISA*/

SELECT NOME, SEXO, ENDEREÇO FROM CLIENTE
WHERE ENDEREÇO LIKE '%CENTRO%';


/*  OPERADORES LÓGICOS:

OR: PARA QUE A SAÍDA SEJA VERDADEIRA, APENAS UMA CONDIÇÃO PRECISA ESTAR VERDADEIRA.
AND: PARA QUE A SAÍDA SEJA VERDADEIRA, TODAS AS CONDIÇÕES PRESCISAM SER VERDADEIRAS.

 */

/* OR - OU */

SELECT * FROM CLENTE;

SELECT NOME, SEXO, ENDEREÇO FROM CLIENTE
WHERE
SEXO = 'M' OR ENDEREÇO LIKE '%RJ';

SELECT NOME, SEXO, ENDEREÇO FROM CLIENTE
WHERE
SEXO = 'F' OR ENDEREÇO LIKE '%ESTACIO';


/* AND - E */

SELECT NOME, SEXO, ENDEREÇO FROM CLIENTE
WHERE
SEXO = 'M' AND ENDEREÇO LIKE '%RJ';

SELECT NOME, SEXO, ENDEREÇO FROM CLIENTE
WHERE
SEXO = 'M' AND ENDEREÇO LIKE '%RJ';


/* COUNT (*), GROUP BY - PERFORMACE COM OPERADORES LÓGICOS */

/* CONTANDO OS REGISTROS DE UM TABELA */

SELECT COUNT(*) AS 
FROM CLIENTE;


/* OPERADOR GROUP BY */

SELECT SEXO, COUNT(*)
FROM CLIENTE;

SELECT * FROM CLIENTE;

SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO;


/* FILTRANDO VALORES NUJLOS */

SELECT NOME, SEXO, ENDEREÇO
FROM CLIENTE
WHERE EMAIL = 'F';

SELECT NOME, SEXO, ENDEREÇO
FROM CLIENTE
WHERE EMAIL IS NULL;

SELECT NOME, SEXO, ENDEREÇO
FROM CLIENTE
WHERE EMAIL IS NOT NULL;  /* QUANDO O LOCAL NÃO ESTIVER VAZIO/NULO */


/* UTILIZANDO O UPDATE PARA ATUALIZAR VALORES */

SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'LILIAN@HOTMAIL.COM';

SELECT NOME, EMAIL
FROM CLIENTE;

SELECT * FROM CLIENTE
WHERE NOME = 'LILIAN';

SELECT * FROM CLIENTE
SET EMAIL = 'JOAOOA@IG.COM.BR'
WHERE NOME = 'JOÃO';


/* DELETANDO REGISTROS */

DELETE FROM CLIENTE; /* SEMPRE EM CONJUNT COM WHERE */


SELECT * FROM CLIENTE
WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE; -- TOTAL: 6

DELETE FROM CLIENTE
WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE; -- TOTAL DELETADO: 1