/* MODELAGEM BÁSICA */

CLIENTE

NOME - CARACTER (30)
CPF - NUMÉRICO (11)
EMAIL - CARACTER (30)
TELEFONE - CARACTER (30)
ENDEREÇO - CARACTER (100)
SEXO - CARACTER (1)

/* PROCESSOS DE MODELAGEM*/

/* FASE 01 E 02 - AD ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE EXEMPLO;

CREATE DATABASE PROJECT;

/* CONECTAND-SE AO BANCO */

USE PROJECT;

/* CRIANDO A TABELA DE CLIENTES */

CREATE TABLE CLIENTE (
    NOME VARCHAR (30),
	SEXO CHAR (1),
	EMAIL VARCHAR (30),
	CPF INT (11),
	TELEFONE VARCHAR (30),
	ENDEREÇO VARCHAR (100)
	/* COPIAR E COLAR NO PROMPT DE COMANDO*/
);

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;

/* DESCOBRINDO A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;